"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { courseFeatureLabels, courseOperationLabels, courseTypeLabels, type CourseFilters, type CourseType, type PublicCoursePage, type CourseHolesFilter, type CourseOperation, type CourseFeatureCode } from "@/lib/courses/courseDirectory";
import { courseProvinces, type CourseProvince, type CourseRegionOption } from "@/lib/courses/courseRegions";
import { courseSearchHref, courseDetailHref, type CourseView } from "@/lib/courses/courseNavigation";
import { CourseInterestBatchProvider, CourseInterestBatchButton } from "./CourseInterestBatch";
import { hasCourseCoordinates } from "@/lib/courses/courseDirections";

const input = "min-h-12 w-full rounded-lg border border-pul-border bg-white px-3 text-base";
const button = "inline-flex min-h-11 items-center justify-center rounded-lg border border-pul-border px-4 text-sm font-bold";
export function CourseMapExplorer({ page, initialFilters, error, view = "list", regionOptions = [], regionError = false }: { page: PublicCoursePage; initialFilters: CourseFilters; error?: string; view?: CourseView; regionOptions?: CourseRegionOption[]; regionError?: boolean }) {
  const router = useRouter();
  const [filters, setFilters] = useState<CourseFilters>({ ...initialFilters, holes: initialFilters.courseType === "field" ? initialFilters.holes : undefined });
  const pageNumber = Math.floor(page.offset / page.limit) + 1;
  const returnTo = courseSearchHref(initialFilters, pageNumber, view);
  const districts = regionOptions.find(option => option.province === filters.province)?.districts ?? [];
  function search(event: FormEvent) { event.preventDefault(); router.push(courseSearchHref(filters, 1, view)); }
  function changeType(courseType?: CourseType) { const next = { ...filters, courseType, hasYardage: courseType === "screen" ? false : filters.hasYardage, holes: courseType === "field" ? filters.holes : undefined }; setFilters(next); router.push(courseSearchHref(next, 1, view)); }
  return <CourseInterestBatchProvider courseKeys={page.items.map(course => course.courseKey)}><section aria-label="골프장 검색과 결과" className="space-y-5">
    <div className="rounded-xl border border-pul-border bg-white p-4 sm:p-6">
      <div role="group" aria-label="골프장 유형" className="flex flex-wrap gap-2 border-b border-pul-border pb-4">
        {([[undefined,"전체"],["field","야외 파크골프장"],["screen","스크린 파크골프장"]] as const).map(([type,label]) => <button key={label} type="button" onClick={() => changeType(type)} aria-pressed={filters.courseType === type} className={`${button} ${filters.courseType === type ? "bg-pul-point text-white" : "bg-white text-pul-deep"}`}>{label}</button>)}
      </div>
      <form onSubmit={search} className="mt-5 space-y-4">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_2fr_auto]">
          <label className="space-y-2 text-sm font-bold">시·도<select className={input} value={filters.province ?? ""} onChange={event => setFilters({ ...filters, region: undefined, province: (event.target.value || undefined) as CourseProvince | undefined, district: undefined })}><option value="">전체 시·도</option>{courseProvinces.map(value => <option key={value}>{value}</option>)}</select></label>
          <label className="space-y-2 text-sm font-bold">시·군·구<select className={input} disabled={!filters.province || regionError} value={filters.district ?? ""} onChange={event => setFilters({ ...filters, district: event.target.value || undefined })}><option value="">전체 시·군·구</option>{filters.district && !districts.includes(filters.district) ? <option>{filters.district}</option> : null}{districts.map(value => <option key={value}>{value}</option>)}</select></label>
          <label className="space-y-2 text-sm font-bold">검색어<input className={input} maxLength={100} value={filters.keyword ?? ""} onChange={event => setFilters({ ...filters, keyword: event.target.value })} placeholder="구장명 또는 주소" /></label>
          <button type="submit" className={`${button} min-h-12 self-end bg-pul-point text-white`}>검색</button>
        </div>
        {regionError ? <p role="status" className="text-sm text-pul-muted">하위 지역을 불러오지 못했습니다. 시·도나 검색어로 찾아주세요.</p> : null}
        {filters.region ? <p className="text-sm">기존 권역 조건: {filters.region} <button type="button" className="min-h-11 underline" onClick={() => setFilters({ ...filters, region: undefined })}>해제</button></p> : null}
        <fieldset><legend className="text-sm font-bold">자료·대회</legend><div className="flex flex-wrap gap-x-5 gap-y-1">{([["hasEvent","대회 예정·진행 중"],["hasVideo","동영상 있음"],...(filters.courseType !== "screen" ? [["hasYardage","야디지북 있음"]] : [])] as ["hasEvent"|"hasVideo"|"hasYardage",string][]).map(([key,label])=><label key={key} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={!!filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.checked})}/>{label}</label>)}</div><p className="text-xs text-pul-muted">여러 조건을 선택하면 모두 충족하는 구장을 찾습니다.</p></fieldset>
        <details className="border-t border-pul-border pt-3"><summary className="cursor-pointer py-2 font-bold">추가 필터</summary><div className="mt-3 grid gap-4 sm:grid-cols-2">
          <label className="text-sm font-bold">이용 방식<select className={`${input} mt-2`} value={filters.operation ?? ""} onChange={event => setFilters({ ...filters, operation: (event.target.value || undefined) as CourseOperation | undefined })}><option value="">전체</option>{Object.entries(courseOperationLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>
          {filters.courseType === "field" ? <label className="text-sm font-bold">야외 홀 수<select className={`${input} mt-2`} value={filters.holes ?? ""} onChange={event => setFilters({ ...filters, holes: (event.target.value || undefined) as CourseHolesFilter | undefined })}><option value="">전체</option><option value="9">9홀</option><option value="18">18홀</option><option value="27_plus">27홀 이상</option></select></label> : null}
          <fieldset className="sm:col-span-2"><legend className="text-sm font-bold">시설·활동</legend><div className="mt-2 flex flex-wrap gap-4">{Object.entries(courseFeatureLabels).map(([code,label]) => <label key={code} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={filters.features?.includes(code as CourseFeatureCode) ?? false} onChange={event => setFilters({ ...filters, features: event.target.checked ? [...(filters.features ?? []), code as CourseFeatureCode] : filters.features?.filter(value => value !== code) })} />{label}</label>)}</div></fieldset>
        </div><button type="submit" className={`${button} mt-3`}>필터 적용</button></details>
      </form>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">{error ? "검색 결과" : `검색 결과 ${page.total.toLocaleString("ko-KR")}곳`}</h2><div className="flex gap-2">{(["list","map"] as const).map(value => <Link key={value} href={courseSearchHref(initialFilters, pageNumber, value)} aria-current={view === value ? "page" : undefined} className={`${button} ${view === value ? "bg-pul-deep text-white" : "bg-white"}`}>{value === "list" ? "목록" : "지도"}</Link>)}</div></div>
    {view === "map" ? <div className="rounded-xl border border-pul-border bg-white p-6"><h3 className="font-bold">지도 연결 준비 중</h3><p className="mt-2 text-sm text-pul-muted">아래 목록에서 구장을 찾고, 상세의 길찾기를 이용해 주세요.</p></div> : null}
    {error ? <div role="alert" className="rounded-xl border border-rose-200 bg-white p-5"><p>{error}</p><button className={`${button} mt-3`} onClick={() => router.refresh()}>다시 불러오기</button></div> : page.items.length === 0 ? <div className="rounded-xl border border-pul-border bg-white p-6"><p>{page.total > 0 ? "이 페이지에 표시할 구장이 없습니다." : "조건에 맞는 구장이 없습니다."}</p><Link className={`${button} mt-3`} href={page.total > 0 ? courseSearchHref(initialFilters, 1, view) : "/courses"}>{page.total > 0 ? "첫 페이지" : "조건 초기화"}</Link></div> : <ul className="space-y-3">{page.items.map(course => <li key={course.courseKey} className="rounded-xl border border-pul-border bg-white p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold text-pul-point">{courseTypeLabels[course.courseType]}{course.courseType === "field" ? ` · ${course.holes}홀` : course.bayCount === null ? " · 타석 수 확인 중" : ` · ${course.bayCount}타석`}</p><Link href={courseDetailHref(course.courseKey, returnTo)} className="mt-2 block break-words text-xl font-bold text-pul-deep hover:underline">{course.name}</Link><p className="mt-2 break-words text-sm leading-6 text-pul-muted">{course.address}</p></div><CourseInterestBatchButton courseKey={course.courseKey} returnTo={returnTo} /></div><div className="mt-4 grid gap-2 border-t border-pul-border pt-4 text-sm leading-6 sm:grid-cols-3"><p className="line-clamp-2">시간 · {course.operatingHours ?? "확인 중"}</p><p className="line-clamp-2">요금 · {course.feeGuide ?? "확인 중"}</p><p>{course.operation ? courseOperationLabels[course.operation] : "이용 방식 확인 중"} · 주차 {course.parkingAvailable === true ? "가능" : course.parkingAvailable === false ? "불가" : "확인 중"}</p></div>{course.resourceCounts ? <p className="mt-3 flex flex-wrap gap-3 text-xs font-bold text-pul-point">{course.resourceCounts.event > 0 ? <span>예정·진행 대회 {course.resourceCounts.event}건</span> : null}{course.resourceCounts.video > 0 ? <span>동영상 {course.resourceCounts.video}개</span> : null}{course.courseType !== "screen" && course.resourceCounts.yardage > 0 ? <span>야디지북 {course.resourceCounts.yardage}개</span> : null}</p> : null}{!hasCourseCoordinates(course) ? <p className="mt-2 text-xs text-pul-muted">위치 확인 중</p> : null}</li>)}</ul>}
    {!error && page.total > 0 ? <nav aria-label="검색 결과 페이지" className="flex items-center justify-center gap-3">{pageNumber > 1 ? <Link className={button} href={courseSearchHref(initialFilters, pageNumber - 1, view)}>이전</Link> : null}<span className="text-sm">{pageNumber} / {Math.ceil(page.total / page.limit)} 페이지</span>{page.hasMore ? <Link className={button} href={courseSearchHref(initialFilters, pageNumber + 1, view)}>다음</Link> : null}</nav> : null}
  </section></CourseInterestBatchProvider>;
}
