import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {createRequire} from "node:module";
import vm from "node:vm";
const require=createRequire(import.meta.url),ts=require("typescript"),sharp=require("sharp");
function load(path,deps){const exports={};vm.runInNewContext(ts.transpileModule(readFileSync(new URL(path,import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:p=>deps[p],Buffer,process:{env:{SUPABASE_SERVICE_ROLE_KEY:"synthetic-service"}}});return exports;}
const policy=load("../images/photoPolicy.ts",{}),validation=load("../images/validatePhotoBytes.ts",{"server-only":{},sharp,"./photoPolicy":policy}),legacy=load("hallOfFameEvidenceValidation.ts",{});
function scenario(bytes,mime){const calls=[];const service={storage:{from:()=>({download:async()=>({data:new Blob([bytes],{type:mime}),error:null})})},rpc:async name=>{calls.push(name);if(name==="get_hall_of_fame_evidence_upload_context_server")return{data:{evidence_id:"evidence",storage_bucket:"private-evidence",storage_path:"owned",declared_mime_type:mime,declared_byte_size:bytes.length,upload_expires_at:"2027-01-01",evidence_version:1,batch_version:1},error:null};if(name==="finalize_hall_of_fame_evidence_server")return{data:{evidence_id:"evidence",status:"ready",evidence_version:2,batch_version:2,record_version:2},error:null};return{data:null,error:null}}};const api=load("hallOfFameEvidenceStorage.ts",{"server-only":{},"node:crypto":require("node:crypto"),"@supabase/supabase-js":{createClient:()=>service},"@/lib/supabase/env":{getSupabasePublicEnv:()=>({url:"http://local.invalid"})},"@/lib/supabase/auth":{getAuthenticatedSupabaseContext:async()=>({userId:"synthetic-actor",supabase:{}})},"@/lib/hall-of-fame/hallOfFameEvidenceValidation":legacy,"@/lib/images/validatePhotoBytes":validation});return{calls,run:()=>api.finalizeHallOfFameEvidence({evidenceId:"evidence",expectedEvidenceVersion:1,expectedBatchVersion:1,requestId:"synthetic-request"})};}
test("scorecard actual pixels are checked before server completion, including small-byte large-pixel files",async()=>{const bytes=await sharp({create:{width:2561,height:1,channels:3,background:"#fff"}}).png().toBuffer();const s=scenario(bytes,"image/png");await assert.rejects(s.run(),/HOF_EVIDENCE_OBJECT_VALIDATION_FAILED/);assert.ok(s.calls.includes("mark_hall_of_fame_evidence_failed_server"));assert.ok(!s.calls.includes("finalize_hall_of_fame_evidence_server"));});
test("valid 2560px scorecard and legacy PDF retain the existing server completion path",async()=>{const bytes=await sharp({create:{width:2560,height:100,channels:3,background:"#fff"}}).png().toBuffer();for(const [file,mime]of[[bytes,"image/png"],[Buffer.from("%PDF-1.4\nsynthetic"),"application/pdf"]]){const s=scenario(file,mime);assert.equal((await s.run()).status,"ready");assert.ok(s.calls.includes("finalize_hall_of_fame_evidence_server"));}});
