"use client";
/* eslint-disable @next/next/no-img-element -- Private store media checks visibility on every uncached request. */
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {loadStoresAction} from "@/app/market/storeActions";
import {MarketInterest} from "@/components/interests/MarketInterest";
import {StoreEditor,storeButton,storeInput} from "./StoreEditor";
import {storeHref,storeFilters,storeStatuses,storeRegions,storeMoney,depositModes,parkingModes,type StorePage,type StoreRow} from "@/lib/market/marketStores";
function StoreFacts({row,full=false}:{row:StoreRow;full?:boolean}){const p=row.profile;const values=[["지역·층수",p.region+" · "+p.floor],["면적·타석",p.area+(p.areaUnit==="sqm"?"㎡":"평")+" · "+p.bays+"타석"],["프로그램·장비",p.equipment],["임대 보증금",storeMoney(p.deposit)],["월세·관리비",storeMoney(p.rent)+" / "+storeMoney(p.maintenance)],["주차",parkingModes[p.parking]+(full&&p.parkingNote?" · "+p.parkingNote:"")],...(full?[["운영시간",p.hours||"미기재"],["양도 범위",p.facilities]]:[])];return <dl className="grid min-w-0 grid-cols-[6.5rem_minmax(0,1fr)] gap-x-3 gap-y-2 text-sm leading-6">{values.map(([k,v])=><div key={k} className="contents"><dt className="text-pul-muted">{k}</dt><dd className="min-w-0 whitespace-pre-wrap [overflow-wrap:anywhere]">{v}</dd></div>)}</dl>;}
function Price({row}:{row:StoreRow}){const p=row.profile;return <div className="min-w-0"><p className="text-xs text-pul-muted">양도 희망금액</p><p className="text-2xl font-bold tracking-tight [overflow-wrap:anywhere]">{storeMoney(p.askingPrice)}</p><p className="mt-1 text-sm">{depositModes[p.depositMode]}{p.negotiable?" · 금액 협의 가능":""}</p></div>;}
export function MarketStores({search,userId,manage=false}:{search:string;userId:string|null;manage?:boolean}){
 const router=useRouter(),params=new URLSearchParams(search),storeId=params.get("store"),writing=!manage&&params.get("store_write")==="1";
 const [data,setData]=useState<StorePage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0),[message,setMessage]=useState("");
 const [edit,setEdit]=useState<{row:StoreRow;mode:"edit"|"status"|"delete"}|null>(null);
 useEffect(()=>{let live=true;loadStoresAction(search,manage).then(x=>{if(live){setData(x);setLoading(false);setError(false);}}).catch(()=>{if(live){setLoading(false);setError(true);}});return()=>{live=false;};},[search,manage,retry]);
 const href=(change:Record<string,string>)=>storeHref(search,change),listHref=href({store:"",store_write:""});
 const login=(next:string)=>"/login?next="+encodeURIComponent(next);
 function refresh(){setLoading(true);setError(false);setRetry(x=>x+1);}
 function done(r:{id:string;deleted:boolean}){setEdit(null);setMessage("저장은 완료되었습니다.");if(manage||(!r.deleted&&r.id===storeId))refresh();else router.push(href({store:r.deleted?"":r.id,store_write:""}));}
 const controls=(row:StoreRow)=>row.mine?<div className="flex flex-wrap gap-2"><button className={storeButton} onClick={()=>setEdit({row,mode:"edit"})}>매장 정보 수정</button><button className={storeButton} onClick={()=>setEdit({row,mode:"status"})}>거래 상태 변경</button><button className={storeButton} onClick={()=>setEdit({row,mode:"delete"})}>매장 글 삭제</button></div>:null;
 let offset=0;try{offset=storeFilters(search).offset;}catch{/* Query failure is shown below. */}
 const pageHref=(next:number)=>manage?"/market/stores?"+new URLSearchParams({...Object.fromEntries(params),store_offset:String(next)}):href({store_offset:String(next)});
 const row=data?.detail;
 return <section aria-label={manage?"내 매장 글 관리":"매장매매"} className="min-w-0 space-y-4">
 <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{manage?"내 매장 글 관리":"매장매매"}</h2><p className="mt-1 text-sm leading-6 text-pul-muted">운영 중인 스크린파크골프 매장의 양도 정보를 비교해 보세요.</p></div>{!writing&&!edit?<div className="flex flex-wrap gap-2"><Link className={storeButton+" bg-pul-point text-white"} href={userId?href({store:"",store_write:"1"}):login(href({store:"",store_write:"1"}))}>매장 등록</Link>{!manage?<Link className={storeButton} href="/market/stores">내 매장 글 관리</Link>:null}</div>:null}</div>
 {message?<p role="status" className="text-sm text-pul-point">{message}</p>:null}
 {writing?userId?<StoreEditor onDone={done} onCancel={()=>router.push(listHref)}/>:<Link className={storeButton} href={login(href({store_write:"1"}))}>로그인 후 매장 등록</Link>:edit?<StoreEditor key={edit.row.id+edit.mode} row={edit.row} mode={edit.mode} onDone={done} onCancel={()=>setEdit(null)}/>:<>
 {storeId&&!manage?<><Link className={storeButton} href={listHref}>← 매장 목록</Link>{!loading&&!error&&row?<article className="min-w-0 space-y-5 rounded-xl border border-pul-border bg-white p-4 sm:p-6"><div><p className="text-sm font-bold text-pul-point">{storeStatuses[row.status]}</p><h3 className="mt-2 text-2xl font-bold [overflow-wrap:anywhere]">{row.profile.title}</h3><p className="mt-2 text-sm text-pul-muted">{row.author} · 작성자 제공 정보</p></div><div className="flex flex-wrap items-center justify-between gap-4 rounded-lg bg-pul-light/30 p-4"><Price row={row}/><div className="flex flex-wrap gap-2">{row.contactable&&!row.mine?<Link className={storeButton+" bg-pul-point text-white"} href={userId?"/messages/new?store="+row.id:login("/messages/new?store="+row.id)}>매장 주인에게 문의</Link>:<p className="self-center text-sm">{row.mine?"내가 등록한 매장입니다.":row.status==="completed"?"거래 완료 · 신규 문의 종료":"신규 문의를 받을 수 없습니다."}</p>}<MarketInterest kind="store" id={row.id} authenticated={Boolean(userId)}/></div></div>{controls(row)}<div className="grid min-w-0 gap-3 sm:grid-cols-2">{row.profile.photos.map((id,i)=><img key={id} src={"/market/store-media/"+id} alt={i===0?"매장 대표 사진":"매장 사진 "+(i+1)} className={(i===0?"sm:col-span-2 ":"")+"aspect-[16/10] w-full rounded-lg bg-pul-page object-contain"}/>)}</div><h4 className="font-bold">매장·임대 조건</h4><StoreFacts row={row} full/><h4 className="font-bold">운영 설명</h4><p className="whitespace-pre-wrap leading-7 [overflow-wrap:anywhere]">{row.profile.description}</p><div className="rounded-lg border border-pul-border p-4"><h4 className="font-bold">선택 재무 정보</h4><p className="mt-1 text-sm text-pul-muted">작성자 제공 · 증빙 확인 안 됨</p><p className="mt-1 text-sm">기준 기간: {row.profile.financePeriod||"미기재"}</p><dl className="mt-3 grid min-w-0 gap-3 sm:grid-cols-3">{([['매출',row.profile.revenue],['비용',row.profile.cost],['순이익',row.profile.profit]] as const).map(([label,n])=><div key={label} className="min-w-0"><dt className="text-sm text-pul-muted">{label}</dt><dd className="font-bold [overflow-wrap:anywhere]">{storeMoney(n)}</dd></div>)}</dl></div></article>:!loading&&!error?<p role="status">삭제되었거나 볼 수 없는 매장 글입니다.</p>:null}</>:<>
 <form aria-label="매장 검색" className="grid min-w-0 grid-cols-2 items-end gap-2 sm:grid-cols-[minmax(0,1fr)_9rem_9rem_auto]" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),values={store_q:String(f.get("q")??"").trim(),store_region:String(f.get("region")??""),store_status:String(f.get("status")??""),store_offset:"",store:"",store_write:""};router.push(manage?"/market/stores?"+new URLSearchParams(Object.fromEntries(Object.entries({...Object.fromEntries(params),...values}).filter(([,v])=>v))):href(values));}}><label className="col-span-2 min-w-0 text-sm sm:col-span-1">매장 검색<input name="q" className={storeInput} maxLength={100} defaultValue={params.get("store_q")??""} placeholder="제목·프로그램·운영 설명"/></label><label className="min-w-0 text-sm">지역<select name="region" className={storeInput} defaultValue={params.get("store_region")??""}><option value="">전체 지역</option>{storeRegions.map(x=><option key={x}>{x}</option>)}</select></label><label className="min-w-0 text-sm">거래 상태<select name="status" className={storeInput} defaultValue={params.get("store_status")??""}><option value="">전체 상태</option>{Object.entries(storeStatuses).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><button className={storeButton+" col-span-2 bg-pul-point text-white sm:col-span-1"}>검색</button></form>
 {!loading&&!error?<><div className="grid min-w-0 gap-4 md:grid-cols-2 xl:grid-cols-3">{data?.items.map(r=><article key={r.id} className="min-w-0 overflow-hidden rounded-xl border border-pul-border bg-white"><Link className="block" href={href({store:r.id,store_write:""})}><img src={"/market/store-media/"+r.profile.photos[0]} alt="" className="aspect-[16/9] w-full bg-pul-page object-cover"/><div className="space-y-2 p-4"><p className="text-xs font-bold text-pul-point">{storeStatuses[r.status]} · {r.profile.region}</p><h3 className="text-lg font-bold [overflow-wrap:anywhere]">{r.profile.title}</h3><Price row={r}/></div></Link><div className="space-y-3 px-4 pb-4"><StoreFacts row={r}/><MarketInterest kind="store" id={r.id} authenticated={Boolean(userId)}/>{manage?controls(r):null}</div></article>)}</div>{!data?.items.length?<p className="rounded-lg bg-white p-5 text-sm">{manage?"조건에 맞는 내 매장 글이 없습니다.":"조건에 맞는 매장 글이 없습니다."}</p>:null}{offset>0||data?.hasMore?<nav aria-label="매장 페이지" className="flex flex-wrap justify-center gap-3">{offset>0?<Link className={storeButton} href={pageHref(Math.max(0,offset-12))}>이전</Link>:null}<span className="self-center text-sm">{Math.floor(offset/12)+1} 페이지</span>{data?.hasMore?<Link className={storeButton} href={pageHref(offset+12)}>다음</Link>:null}</nav>:null}</>:null}
 </>}
 {loading?<p role="status">매장 정보를 불러오는 중…</p>:null}{error?<div role="alert" className="rounded-lg border p-4 text-sm">매장 정보를 불러오지 못했습니다. <button className={storeButton} onClick={refresh}>다시 시도</button></div>:null}
 </>}
 <aside className="border-t border-pul-border pt-4 text-sm leading-6 text-pul-muted">등록 정보는 작성자가 제공합니다. 임대차·시설·운영 자료와 양도 조건은 당사자에게 확인해 주세요.</aside>
 </section>;
}
