-- Keep private schema closed to callers. Fixed public wrappers retain the exact role grants and JWT checks.
begin;
alter function public.course_content_list(text,text,integer,integer,boolean) security definer;
alter function public.course_content_list(text,text,integer,integer,boolean) owner to postgres;
revoke all on function private.course_content_list(text,text,integer,integer,boolean) from public,anon,authenticated,service_role;
alter function public.course_content_detail(uuid) security definer;
alter function public.course_content_detail(uuid) owner to postgres;
revoke all on function private.course_content_detail(uuid) from public,anon,authenticated,service_role;
alter function public.course_content_overview(text) security definer;
alter function public.course_content_overview(text) owner to postgres;
revoke all on function private.course_content_overview(text) from public,anon,authenticated,service_role;
alter function public.course_content_notices(text,integer,integer) security definer;
alter function public.course_content_notices(text,integer,integer) owner to postgres;
revoke all on function private.course_content_notices(text,integer,integer) from public,anon,authenticated,service_role;
alter function public.course_content_image_read(uuid) security definer;
alter function public.course_content_image_read(uuid) owner to postgres;
revoke all on function private.course_content_image_read(uuid) from public,anon,authenticated,service_role;
alter function public.course_content_mutate(text,text,uuid,integer,uuid,jsonb) security definer;
alter function public.course_content_mutate(text,text,uuid,integer,uuid,jsonb) owner to postgres;
revoke all on function private.course_content_mutate(text,text,uuid,integer,uuid,jsonb) from public,anon,authenticated,service_role;
alter function public.course_content_workspace(text) security definer;
alter function public.course_content_workspace(text) owner to postgres;
revoke all on function private.course_content_workspace(text) from public,anon,authenticated,service_role;
alter function public.course_content_notice_mutate(text,text,uuid,integer,uuid,jsonb) security definer;
alter function public.course_content_notice_mutate(text,text,uuid,integer,uuid,jsonb) owner to postgres;
revoke all on function private.course_content_notice_mutate(text,text,uuid,integer,uuid,jsonb) from public,anon,authenticated,service_role;
alter function public.course_content_notice_send(uuid,integer,uuid) security definer;
alter function public.course_content_notice_send(uuid,integer,uuid) owner to postgres;
revoke all on function private.course_content_notice_send(uuid,integer,uuid) from public,anon,authenticated,service_role;
alter function public.course_content_set_recipient(text,uuid,integer,uuid) security definer;
alter function public.course_content_set_recipient(text,uuid,integer,uuid) owner to postgres;
revoke all on function private.course_content_set_recipient(text,uuid,integer,uuid) from public,anon,authenticated,service_role;
alter function public.course_content_send_inquiry(text,text,uuid) security definer;
alter function public.course_content_send_inquiry(text,text,uuid) owner to postgres;
revoke all on function private.course_content_send_inquiry(text,text,uuid) from public,anon,authenticated,service_role;
alter function public.course_content_message_context(uuid) security definer;
alter function public.course_content_message_context(uuid) owner to postgres;
revoke all on function private.course_content_message_context(uuid) from public,anon,authenticated,service_role;
alter function public.course_content_image_prepare(uuid,text,uuid,text,integer,text) security definer;
alter function public.course_content_image_prepare(uuid,text,uuid,text,integer,text) owner to postgres;
revoke all on function private.course_content_image_prepare(uuid,text,uuid,text,integer,text) from public,anon,authenticated,service_role;
alter function public.course_content_image_finish(uuid,uuid,text) security definer;
alter function public.course_content_image_finish(uuid,uuid,text) owner to postgres;
revoke all on function private.course_content_image_finish(uuid,uuid,text) from public,anon,authenticated,service_role;
alter function public.course_content_event_occurrence(text,text,integer) security definer;
alter function public.course_content_event_occurrence(text,text,integer) owner to postgres;
revoke all on function private.course_content_event_occurrence(text,text,integer) from public,anon,authenticated,service_role;
alter function public.course_content_directory(text,text,text,text,text,text,text,text[],boolean,boolean,boolean,integer,integer) security definer;
alter function public.course_content_directory(text,text,text,text,text,text,text,text[],boolean,boolean,boolean,integer,integer) owner to postgres;
revoke all on function private.course_content_directory(text,text,text,text,text,text,text,text[],boolean,boolean,boolean,integer,integer) from public,anon,authenticated,service_role;
commit;
